name: M0nkey Mind
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: /:title/
collections:
  articles:
    output: true
    permalink: /:title/
